#!/bin/sh
# install.sh — install Timey from this source checkout for the current user.
#
# Timey is pure Python running on top of your distro's GTK 4 / Libadwaita /
# PyGObject packages, so there is nothing to compile and no pip step needed.
# This script:
#   1. checks that the GTK 4 / Libadwaita / PyGObject bindings are present
#   2. copies the pure-Python `timey` package to   $PREFIX/lib/timey/
#   3. creates a `timey` launcher in               $PREFIX/bin/
#   4. registers an app-grid entry + icon under    $PREFIX/share/
#
# Defaults to ~/.local (no root required). Override the location with
# PREFIX=/some/path ./install.sh. Run ./install.sh --uninstall to remove
# everything this script created.
set -eu

APP_ID="io.github.pixlpixlpixl.Timey"
PREFIX="${PREFIX:-$HOME/.local}"
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PYTHON_BIN="${PYTHON:-$(command -v python3 || true)}"

usage() {
    echo "Usage: ./install.sh [--uninstall]"
    echo
    echo "  Installs Timey from the current checkout for the current user."
    echo "  Default prefix: \$HOME/.local   (override with PREFIX=...)"
}

distro_hint() {
    # shellcheck disable=SC1090
    id="$(. /etc/os-release 2>/dev/null; printf '%s' "${ID_LIKE:-$ID}")"
    case "$id" in
        *arch*)   echo "sudo pacman -S python-gobject gtk4 libadwaita" ;;
        *debian*|*ubuntu*) echo "sudo apt install python3-gi gir1.2-gtk-4.0 gir1.2-adw-1" ;;
        *fedora*|*rhel*|*centos*) echo "sudo dnf install python3-gobject gtk4 libadwaita" ;;
        *)        echo "install python3 with GObject introspection plus the GTK 4 and Libadwaita dev/runtime packages" ;;
    esac
}

check_runtime_deps() {
    if [ -z "$PYTHON_BIN" ] || [ ! -x "$PYTHON_BIN" ]; then
        echo "error: python3 not found." >&2
        echo "On this system try:  $(distro_hint)" >&2
        exit 1
    fi
    if ! "$PYTHON_BIN" -c 'import gi; gi.require_version("Gtk", "4.0"); gi.require_version("Adw", "1"); from gi.repository import Gtk, Adw' 2>/dev/null; then
        echo "error: Timey needs the system GTK 4 / Libadwaita / PyGObject bindings." >&2
        echo "On this system try:  $(distro_hint)" >&2
        exit 1
    fi
}

install_app() {
    check_runtime_deps

    lib_dir="$PREFIX/lib/timey"
    desktop_file="$PREFIX/share/applications/$APP_ID.desktop"
    icon_src="$ROOT/packaging/$APP_ID.svg"
    icon_dst="$PREFIX/share/icons/hicolor/scalable/apps/$APP_ID.svg"

    if [ ! -f "$icon_src" ] || [ ! -f "$ROOT/packaging/timey.desktop" ]; then
        echo "error: packaging files not found next to install.sh." >&2
        exit 1
    fi

    # 1. the package itself (a plain source copy, caches excluded)
    rm -rf "$lib_dir"
    mkdir -p "$lib_dir" "$PREFIX/bin" \
        "$PREFIX/share/applications" \
        "$PREFIX/share/icons/hicolor/scalable/apps"
    cp -R "$ROOT/timey" "$lib_dir/"
    find "$lib_dir" -type d -name __pycache__ -prune -exec rm -rf {} +

    # 2. launcher script
    cat > "$PREFIX/bin/timey" <<EOF
#!/bin/sh
# Timey launcher — generated by install.sh; re-run install.sh to regenerate.
export PYTHONPATH="$lib_dir\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$PYTHON_BIN" -m timey "\$@"
EOF
    chmod +x "$PREFIX/bin/timey"

    # 3. desktop entry (Exec points straight at the launcher) + icon
    sed "s|^Exec=.*|Exec=$PREFIX/bin/timey|" "$ROOT/packaging/timey.desktop" \
        > "$desktop_file"
    cp "$icon_src" "$icon_dst"

    refresh_caches
    echo "Installed Timey from source into $PREFIX"
    if [ "$PREFIX" = "$HOME/.local" ]; then
        echo "  launcher: $PREFIX/bin/timey"
    else
        echo "  launcher: $PREFIX/bin/timey   (run with: $PREFIX/bin/timey)"
    fi
    echo "  app-grid entry: Timey  ($desktop_file)"
    case ":$PATH:" in
        *":$PREFIX/bin:"*) : ;;
        *) echo "  note: add $PREFIX/bin to your PATH to run 'timey' from a terminal." ;;
    esac
    echo "To remove:  ./install.sh --uninstall"
}

uninstall_app() {
    lib_dir="$PREFIX/lib/timey"
    rm -f "$PREFIX/bin/timey"
    rm -rf "$lib_dir"
    rm -f "$PREFIX/share/applications/$APP_ID.desktop"
    rm -f "$PREFIX/share/icons/hicolor/scalable/apps/$APP_ID.svg"
    refresh_caches
    echo "Removed Timey from $PREFIX"
}

refresh_caches() {
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database "$PREFIX/share/applications" >/dev/null 2>&1 || true
    fi
    if command -v gtk-update-icon-cache >/dev/null 2>&1; then
        gtk-update-icon-cache -f -t "$PREFIX/share/icons/hicolor" >/dev/null 2>&1 || true
    fi
}

case "${1:-}" in
    --uninstall|-u) uninstall_app ;;
    --help|-h) usage ;;
    "") install_app ;;
    *) echo "error: unknown argument: $1" >&2; usage >&2; exit 1 ;;
esac
